os: linux
dist: trusty
language: cpp

cache:
  - apt
  - ccache

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - cmake
      - git
      - ccache
      - python3
      - python3-dev
      - python3-pip
      - lua5.3
      - liblua5.3-dev
install:
  - pip install conan
  - conan user
script:
  - conan install .
  - mkdir build && cd build
  - cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER  -G "Unix makefiles"
  - cmake --build .