os: linux
dist: bionic
language: python
python: "3.7"

cache:
  - pip
  - apt
  - ccache

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - clang-format-9
      - python3-dev
      - python3-pip
      - python3-setuptools
install:
  - pip install conan
  - conan user
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan
  - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON
  - cmake --build . --parallel 2
  - sudo pip3 install -r requirements.txt
  - jupyter kernelspec install --user rocketjoed/kernels/ipython
  - pytest core/python_sandbox/test_python_kernel.py
