os: linux
dist: xenial
language: python
python: "3.7"

cache:
  - pip
  - apt
  - ccache

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
install:
  - pip install conan
  - conan user
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan
  - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON -DADDRESS_SANITIZER=ON
  - cmake --build .