os: linux
dist: xenial
language: python
python: "3.7"

cache:
  - apt
  - ccache

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lua5.2
      - liblua5.2-dev
install:
  - pip install conan
  - conan user
script:
  - conan install .
  - mkdir build && cd build
  - cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER  -G "Unix makefiles"
  - cmake --build .