os: linux
dist: xenial
language: python
python: "3.7"

cache:
  - apt
  - ccache

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lua5.2
      - liblua5.2-dev
install:
  - pip install conan
  - conan user
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install .
  - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build .