[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "pybind11>=2.10.0",
    "cmake",
    "ninja; platform_system!='Windows'",
]

build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.args = ["-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
    "--import-mode=importlib",
]
