name: macos

on:
  pull_request:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run:
    name: Run
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
            brew install ninja cmake
            python3 -m pip install --no-cache-dir conan==1.63 --break-system-packages
          - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y  build-essential ninja-build python3-pip python3-dev curl gnupg apt-transport-https  

      - name: conan installation and configuration
        run: |
          pip install conan==1.64.0 pytest==6.2.5
          conan user
          conan profile new default --detect --force
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan config set general.parallel_download=$(nproc)
          conan config set general.cpu_count=$(nproc)
          conan remote add duckstax http://conan.duckstax.com

      - name: download dependencies
        run: |
          mkdir build && cd build
          cp ../conanfile.txt .
          conan install . --build missing -s build_type=Release

      - name: build
        env:
          CC: gcc
        run: |
          cd build
          cmake  -G Ninja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON -DEXAMPLE=ON ..
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest -C -V --output-on-failure

      - name: PyTest
        run: |
          cd build/integration/python/
          pytest
