name: ubuntu 20.04
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04]
        python-version: [ 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
            sudo apt-get update \
            && sudo apt-get install -y \
            python3-pip python3-dev

      - name: conan installation and configuration
        run: |
          pip install conan==1.40.3
          conan user
          conan profile new default --detect --force
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan config set general.parallel_download=$(nproc)
          conan config set general.cpu_count=$(nproc)
          conan remote add cyberduckninja http://conan.cyberduckninja.com:9300

      - name: download dependencies
        run: |
          conan install . --build missing -s build_type=Release

      - name: build
        env:
          CC: gcc
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DADDRESS_SANITIZER=ON
          cmake --build . --parallel 2