name: ubuntu 18.04
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install conan
        run: |
          pip install conan
          conan user
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan

      - name: Run CMake
        env:
          CC: gcc
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON
          cmake --build . --parallel 2